<?php
Configure::write('Comment.engine', 'native');
Configure::write('Oauth.password', 'password');
Configure::write('Session', array('defaults' => 'database'));
Configure::write('Domain.host', 'loc.build.42viral.org');
Configure::write('Domain.scheme', 'http');
Configure::write('Facebook.consumer_key', '158831284148987');
Configure::write('Facebook.consumer_secret', '9d0f4fe03255691acd24e7c2ed084fdd');
Configure::write('GooglePlus.consumer_key', '801462531840-pnqdji5v54rm73gbp44ivgv6fmp6pon6.apps.googleusercontent.com');
Configure::write('GooglePlus.consumer_secret', 'XB6dQFR9eWzESeiuTxEXVxW1');
Configure::write('LinkedIn.consumer_key', '9DyXW-5Tgwgt3dn76H4_FrjeEyGwuQSrX1r3o6G1_QyIJyfNDgJeHHW9Mf7T2ib0');
Configure::write('LinkedIn.consumer_secret', 'oyp8wH0WigXPw2rAAysWUSGio0ggVtl-V36xfz8KFiTV4Qsb9Bq8ih3tsN9CW40b');
Configure::write('ShortURL.Pointer.blog', 'a');
Configure::write('ShortURL.Pointer.page', 'b');
Configure::write('ShortURL.Pointer.post', 'c');
Configure::write('Theme.set', 'Default');
Configure::write('Twitter.consumer_key', 'YxaK8Z1QqU1S5XdZxFGBQ');
Configure::write('Twitter.consumer_secret', 'suJANJjO6pWTm8XdP5Y2pBVIJdPlL3CTVOiEatI248');
Configure::write('Yahoo.LocalSearch.app_id', '');
Configure::write('Yelp.consumer_key', 'ybDyLrKoknFkCOc4kJEa7A');
Configure::write('Yelp.consumer_secret', '0h0UVi5uRuaMyzxF4j4HYVE4LfE');
